### ISSUE TITLE
nice skid

### ISSUE THREAD

**Issue by enit9747** [Gorkido/Growtopia-Unbanner#1]
shitty skidded pasta from [NotPrab/Mustangs](https://github.com/NotPrab/Mustangs-Unbanner)

**Comment by Gorkido** [comment]
https://github.com/NotPrab/Mustangs-Unbanner/blob/master/LICENSE

![image](https://user-images.githubusercontent.com/81165187/172029528-15a52a6b-735b-4773-b637-fc7ca91a4f95.png)
